-- =====================================================
-- DEU University System - MySQL Schema (UTF8MB4)
-- Generated by ChatGPT on 2025-11-12
-- =====================================================

-- Create and select database
CREATE DATABASE IF NOT EXISTS `deu` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `deu`;

-- Ensure default engine is InnoDB for FK support
SET default_storage_engine=INNODB;

-- =====================================================
-- 1) department
-- =====================================================
DROP TABLE IF EXISTS department;
CREATE TABLE department (
    dept_code      VARCHAR(20)  PRIMARY KEY,
    dept_name      VARCHAR(100),
    college_name   VARCHAR(100),
    dept_phone     VARCHAR(20),
    dept_office    VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =====================================================
-- 2) member
-- =====================================================
DROP TABLE IF EXISTS member;
CREATE TABLE member (
    m_id               VARCHAR(50)  PRIMARY KEY,
    m_pwd              VARCHAR(255),
    m_name             VARCHAR(100),
    m_type             VARCHAR(20),
    m_no               VARCHAR(20) UNIQUE,        -- 학번/교수번호/관리자번호 통합
    m_email            VARCHAR(255) UNIQUE,
    m_phone            VARCHAR(20),
    m_num              VARCHAR(14) UNIQUE,        -- 주민등록번호(암호화 저장 가정)
    m_birth            DATE,
    m_addr             VARCHAR(500),
    dept_code          VARCHAR(20),
    stu_grade          INT,
    enrollment_status  VARCHAR(20),               -- ENROLLED, LEAVE, GRADUATED
    position           VARCHAR(50),
    office_room        VARCHAR(50),
    major_field        VARCHAR(200),
    start_date         DATE,
    CONSTRAINT fk_member_dept
        FOREIGN KEY (dept_code) REFERENCES department(dept_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_member_dept ON member(dept_code);

-- =====================================================
-- 3) subject
-- =====================================================
DROP TABLE IF EXISTS subject;
CREATE TABLE subject (
    s_code    VARCHAR(20) PRIMARY KEY,
    s_name    VARCHAR(200),
    credit    INT,
    s_type    VARCHAR(20),             -- MAJOR, GENERAL, ELECTIVE
    dept_code VARCHAR(20),
    s_desc    VARCHAR(2000),
    CONSTRAINT fk_subject_dept
        FOREIGN KEY (dept_code) REFERENCES department(dept_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_subject_dept ON subject(dept_code);

-- =====================================================
-- 4) course
-- =====================================================
DROP TABLE IF EXISTS course;
CREATE TABLE course (
    course_code        VARCHAR(20) PRIMARY KEY,
    academic_year      INT,
    semester           INT,
    s_code             VARCHAR(20),
    course_class       VARCHAR(10),    -- 01, 02, ...
    professor_no       VARCHAR(20),    -- member.m_no 참조
    max_stu            INT,
    current_students   INT,
    classroom          VARCHAR(50),
    course_time        VARCHAR(100),
    course_objectives  TEXT,
    course_content     TEXT,
    evaluation_method  VARCHAR(1000),
    textbook_info      VARCHAR(1000),
    course_status      VARCHAR(20),    -- OPEN, CLOSED, CANCELLED
    CONSTRAINT fk_course_subject
        FOREIGN KEY (s_code) REFERENCES subject(s_code),
    CONSTRAINT fk_course_professor
        FOREIGN KEY (professor_no) REFERENCES member(m_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_course_subject ON course(s_code);
CREATE INDEX idx_course_prof_no ON course(professor_no);

-- =====================================================
-- 5) board
-- =====================================================
DROP TABLE IF EXISTS board;
CREATE TABLE board (
    board_id    INT AUTO_INCREMENT PRIMARY KEY,
    board_code  VARCHAR(50) UNIQUE,
    board_name  VARCHAR(100),
    write_auth  VARCHAR(50)           -- ADMIN, PROFESSOR
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =====================================================
-- 6) post
-- =====================================================
DROP TABLE IF EXISTS post;
CREATE TABLE post (
    post_id      INT AUTO_INCREMENT PRIMARY KEY,
    board_id     INT,
    post_title   VARCHAR(500),
    post_content TEXT,
    writer_id    VARCHAR(50),          -- member.m_no 참조
    view_count   INT DEFAULT 0,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_post_board
        FOREIGN KEY (board_id) REFERENCES board(board_id),
    CONSTRAINT fk_post_writer
        FOREIGN KEY (writer_id) REFERENCES member(m_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_post_board ON post(board_id);
CREATE INDEX idx_post_writer ON post(writer_id);

-- =====================================================
-- 7) tuition
-- =====================================================
DROP TABLE IF EXISTS tuition;
CREATE TABLE tuition (
    tuition_id        INT AUTO_INCREMENT PRIMARY KEY,
    stu_no            VARCHAR(20),     -- member.m_no 참조
    academic_year     INT,
    semester          INT,             -- 1,2
    tuition_amount    INT,
    scholarship_amount INT,
    paid_amount       INT,
    bill_date         DATE,
    due_date          DATE,
    paid_date         DATE,
    payment_method    VARCHAR(50),
    receipt_no        VARCHAR(50) UNIQUE,
    payment_status    VARCHAR(20),     -- UNPAID, PAID, OVERDUE
    CONSTRAINT fk_tuition_student
        FOREIGN KEY (stu_no) REFERENCES member(m_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_tuition_stu ON tuition(stu_no);

-- =====================================================
-- 8) leave_application
-- =====================================================
DROP TABLE IF EXISTS leave_application;
CREATE TABLE leave_application (
    application_id     INT AUTO_INCREMENT PRIMARY KEY,
    stu_no             VARCHAR(20),     -- member.m_no
    leave_type         VARCHAR(20),     -- GENERAL, MILITARY, ILLNESS, PREGNANCY
    start_year         INT,
    start_semester     INT,
    end_year           INT,
    end_semester       INT,
    application_reason VARCHAR(1000),
    application_date   TIMESTAMP,
    approval_status    VARCHAR(20),     -- PENDING, APPROVED, REJECTED
    approval_date      TIMESTAMP,
    approver_id        VARCHAR(50),     -- member.m_no
    reject_reason      VARCHAR(1000),
    CONSTRAINT fk_leave_student  FOREIGN KEY (stu_no) REFERENCES member(m_no),
    CONSTRAINT fk_leave_approver FOREIGN KEY (approver_id) REFERENCES member(m_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_leave_stu ON leave_application(stu_no);
CREATE INDEX idx_leave_approver ON leave_application(approver_id);

-- =====================================================
-- 9) enrollment
-- =====================================================
DROP TABLE IF EXISTS enrollment;
CREATE TABLE enrollment (
    enrollment_id    INT AUTO_INCREMENT PRIMARY KEY,
    stu_no           VARCHAR(20),     -- member.m_no
    course_code      VARCHAR(20),     -- course.course_code
    enrollment_date  TIMESTAMP,
    enrollment_status VARCHAR(20),    -- ENROLLED, DROPPED, COMPLETED
    cancel_date      TIMESTAMP,
    CONSTRAINT fk_enroll_student FOREIGN KEY (stu_no) REFERENCES member(m_no),
    CONSTRAINT fk_enroll_course  FOREIGN KEY (course_code) REFERENCES course(course_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_enroll_stu ON enrollment(stu_no);
CREATE INDEX idx_enroll_course ON enrollment(course_code);

-- =====================================================
-- 10) grade
-- =====================================================
DROP TABLE IF EXISTS grade;
CREATE TABLE grade (
    grade_id          INT AUTO_INCREMENT PRIMARY KEY,
    enrollment_id     INT UNIQUE,             -- one-to-one
    midterm_score     DECIMAL(5,2),
    final_score       DECIMAL(5,2),
    assignment_score  DECIMAL(5,2),
    attendance_score  DECIMAL(5,2),
    presentation_score DECIMAL(5,2),
    total_score       DECIMAL(5,2),
    grade_letter      VARCHAR(2),
    grade_point       DECIMAL(3,2),          -- 4.5 만점 기준
    CONSTRAINT fk_grade_enroll FOREIGN KEY (enrollment_id) REFERENCES enrollment(enrollment_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =====================================================
-- 11) attendance
-- =====================================================
DROP TABLE IF EXISTS attendance;
CREATE TABLE attendance (
    attendance_id     INT AUTO_INCREMENT PRIMARY KEY,
    enrollment_id     INT,
    attendance_date   DATE,
    period            INT,
    attendance_status VARCHAR(20),    -- PRESENT, ABSENT, LATE, EXCUSED
    remark            VARCHAR(500),
    CONSTRAINT fk_attend_enroll FOREIGN KEY (enrollment_id) REFERENCES enrollment(enrollment_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_attend_enroll ON attendance(enrollment_id);
CREATE INDEX idx_attend_date ON attendance(attendance_date);

-- =====================================================
-- 12) course_evaluation
-- =====================================================
DROP TABLE IF EXISTS course_evaluation;
CREATE TABLE course_evaluation (
    evaluation_id   INT AUTO_INCREMENT PRIMARY KEY,
    course_code     VARCHAR(20),
    stu_no          VARCHAR(20),
    eval1           INT,
    eval2           INT,
    eval3           INT,
    eval4           INT,
    eval5           INT,
    total_score     DECIMAL(3,2),
    comment         VARCHAR(2000),
    evaluation_date TIMESTAMP,
    CONSTRAINT fk_eval_course FOREIGN KEY (course_code) REFERENCES course(course_code),
    CONSTRAINT fk_eval_student FOREIGN KEY (stu_no) REFERENCES member(m_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_eval_course ON course_evaluation(course_code);
CREATE INDEX idx_eval_student ON course_evaluation(stu_no);

-- =====================================================
-- 13) academic_schedule
-- =====================================================
DROP TABLE IF EXISTS academic_schedule;
CREATE TABLE academic_schedule (
    schedule_id       INT AUTO_INCREMENT PRIMARY KEY,
    academic_year     INT,
    semester          INT,                 -- 1,2, 0(전체)
    schedule_title    VARCHAR(200),
    schedule_content  VARCHAR(1000),
    start_date        DATE,
    end_date          DATE,
    background_color  VARCHAR(20),
    recurrence_type   VARCHAR(20)          -- NONE, DAILY, WEEKLY, MONTHLY, YEARLY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =====================================================
-- 14) attachment
-- =====================================================
DROP TABLE IF EXISTS attachment;
CREATE TABLE attachment (
    attachment_id INT AUTO_INCREMENT PRIMARY KEY,
    post_id       INT,
    filename      VARCHAR(500),
    CONSTRAINT fk_attach_post FOREIGN KEY (post_id) REFERENCES post(post_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_attach_post ON attachment(post_id);

-- =====================================================
-- 15) refresh_tokens
-- =====================================================
DROP TABLE IF EXISTS refresh_tokens;
CREATE TABLE refresh_tokens (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    token       VARCHAR(255) NOT NULL UNIQUE,
    expiry_date DATETIME(6) NOT NULL,
    member_id   VARCHAR(50),  -- member.m_id (VARCHAR 50) 와 타입 일치 필수
    CONSTRAINT fk_refresh_token_member
        FOREIGN KEY (member_id) REFERENCES member(m_id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_refresh_token_member ON refresh_tokens(member_id);

-- =====================================================
-- End of schema
-- =====================================================

-- =====================================================
-- Sample Data Insertion
-- =====================================================

-- 관리자 계정 추가 (공지사항 작성자)
INSERT INTO department (dept_code, dept_name, college_name) VALUES ('ADM', '관리부서', '본부');
INSERT INTO member (m_id, m_pwd, m_name, m_type, m_no, m_email, dept_code)
VALUES ('admin', 'admin', '관리자', 'ADMIN', 'admin001', 'admin@deu.ac.kr', 'ADM');

-- 공지사항 게시판 추가
INSERT INTO board (board_code, board_name, write_auth) VALUES ('announcements', '공지사항', 'ADMIN');

-- 샘플 공지사항 추가
INSERT INTO post (board_id, post_title, post_content, writer_id)
SELECT board_id, '2025학년도 2학기 수강신청 안내', '2025학년도 2학기 수강신청이 8월 10일부터 시작됩니다. 학생 여러분의 많은 관심 바랍니다.', 'admin001'
FROM board WHERE board_code = 'announcements';

INSERT INTO post (board_id, post_title, post_content, writer_id)
SELECT board_id, '중앙도서관 리모델링 공사 안내', '중앙도서관이 더 나은 환경을 제공하기 위해 9월 1일부터 12월 31일까지 리모델링 공사를 진행합니다. 이용에 불편을 드려 죄송합니다.', 'admin001'
FROM board WHERE board_code = 'announcements';

INSERT INTO post (board_id, post_title, post_content, writer_id)
SELECT board_id, '2025년 동아리 박람회 개최 안내', '9월 5일부터 7일까지 학생회관 앞에서 2025년 동아리 박람회가 개최됩니다. 다양한 동아리를 만나보세요!', 'admin001'
FROM board WHERE board_code = 'announcements';

-- 컴퓨터공학과 추가
INSERT INTO department (dept_code, dept_name, college_name) VALUES ('CS', '컴퓨터공학과', 'IT융합대학');

-- 샘플 학생 계정 추가
INSERT INTO member (m_id, m_pwd, m_name, m_type, m_no, m_email, dept_code, stu_grade, enrollment_status)
VALUES ('student', '1234', '김학생', 'STUDENT', '20210001', 'student@deu.ac.kr', 'CS', 2, 'ENROLLED');

-- 샘플 교수 계정 추가
INSERT INTO member (m_id, m_pwd, m_name, m_type, m_no, m_email, dept_code, position)
VALUES ('professor', '1234', '이교수', 'PROFESSOR', 'prof001', 'professor@deu.ac.kr', 'CS', '조교수');

-- 추가 학생 계정들 (등록금 테스트용)
INSERT INTO member (m_id, m_pwd, m_name, m_type, m_no, m_email, dept_code, stu_grade, enrollment_status)
VALUES
('student2', '1234', '박민수', 'STUDENT', '20210002', 'student2@deu.ac.kr', 'CS', 2, 'ENROLLED'),
('student3', '1234', '최영희', 'STUDENT', '20210003', 'student3@deu.ac.kr', 'CS', 3, 'ENROLLED'),
('student4', '1234', '정철수', 'STUDENT', '20210004', 'student4@deu.ac.kr', 'CS', 1, 'ENROLLED'),
('student5', '1234', '강지은', 'STUDENT', '20210005', 'student5@deu.ac.kr', 'CS', 4, 'ENROLLED');

-- 샘플 등록금 데이터 추가 (실제 납부금액 = 등록금 - 장학금)
INSERT INTO tuition (stu_no, academic_year, semester, tuition_amount, scholarship_amount, paid_amount, bill_date, due_date, payment_status)
VALUES
('20210001', 2025, 1, 4000000, 1000000, 0, '2025-01-10', '2025-02-10', 'UNPAID'),
('20210002', 2025, 1, 4000000, 2000000, 2000000, '2025-01-10', '2025-02-10', 'PAID'),
('20210003', 2025, 1, 4000000, 500000, 0, '2025-01-10', '2025-02-10', 'UNPAID'),
('20210004', 2025, 1, 4000000, 0, 4000000, '2025-01-10', '2025-02-10', 'PAID'),
('20210005', 2025, 1, 4000000, 3000000, 0, '2025-01-10', '2025-02-10', 'UNPAID');
