
// CSV data converted to JSON array
export const MOCK_REVIEWS = [
  { course_id: 1, prof_name: "홍길동", review_text: "과제 많지만 설명이 정말 자세해서 이해가 잘 됨", rating: 5 },
  { course_id: 1, prof_name: "홍길동", review_text: "말이 너무 빨라서 필기를 못 따라감", rating: 2 },
  { course_id: 1, prof_name: "홍길동", review_text: "중요한 부분을 반복해서 짚어줘서 좋았다", rating: 4 },
  { course_id: 2, prof_name: "김영희", review_text: "출석도 널널하고 편하게 들을 수 있는 꿀강의", rating: 5 },
  { course_id: 2, prof_name: "김영희", review_text: "시험 범위 공지가 늦어서 준비하기 힘들었다", rating: 2 },
  { course_id: 3, prof_name: "이철수", review_text: "ppt만 읽어서 이해가 잘 안 됨", rating: 1 },
  { course_id: 3, prof_name: "이철수", review_text: "예시와 연습문제를 많이 줘서 좋았다", rating: 4 },
  { course_id: 4, prof_name: "박민수", review_text: "조별과제가 많지만 실무에 도움 되는 수업", rating: 4 },
  { course_id: 4, prof_name: "박민수", review_text: "설명도 잘하고 수업 준비가 잘 되어 있음", rating: 5 },
  { course_id: 5, prof_name: "조민재", review_text: "실습 위주라 재밌고 도움이 많이 됨", rating: 5 },
  { course_id: 5, prof_name: "조민재", review_text: "너무 지루해서 집중하기 어려움", rating: 1 },
  { course_id: 2, prof_name: "김영희", review_text: "중요한 부분을 여러 번 강조해줘서 기억에 남는다 전체적으로 만족스러운 강의였다", rating: 5 },
  { course_id: 4, prof_name: "박민수", review_text: "중요한 부분을 여러 번 강조해줘서 기억에 남는다 개인적으로는 아쉬운 점도 있었다", rating: 4 },
  { course_id: 2, prof_name: "김영희", review_text: "난이도는 적당한 편이다", rating: 3 },
  { course_id: 1, prof_name: "홍길동", review_text: "강의 속도와 난이도가 적당하다 개인적으로는 아쉬운 점도 있었다", rating: 4 },
  { course_id: 1, prof_name: "홍길동", review_text: "과제량은 보통 수준이다 개인적으로는 아쉬운 점도 있었다", rating: 3 },
  { course_id: 7, prof_name: "오지훈", review_text: "판서를 깔끔하게 잘 해준다", rating: 5 },
  { course_id: 3, prof_name: "이철수", review_text: "난이도는 적당한 편이다 다시 들어도 괜찮을 것 같다", rating: 3 },
  { course_id: 5, prof_name: "조민재", review_text: "강의 속도와 난이도가 적당하다", rating: 5 },
  { course_id: 2, prof_name: "김영희", review_text: "설명이 두서없고 이해가 잘 안 된다 다시 들어도 괜찮을 것 같다", rating: 2 },
  { course_id: 5, prof_name: "조민재", review_text: "중요한 부분을 여러 번 강조해줘서 기억에 남는다 개인적으로는 아쉬운 점도 있었다", rating: 5 },
  { course_id: 2, prof_name: "김영희", review_text: "설명이 두서없고 이해가 잘 안 된다 개인적으로는 아쉬운 점도 있었다", rating: 2 },
  { course_id: 6, prof_name: "최수진", review_text: "과제량은 보통 수준이다", rating: 3 },
  { course_id: 1, prof_name: "홍길동", review_text: "과제량은 보통 수준이다 다시 들어도 괜찮을 것 같다", rating: 3 },
  { course_id: 2, prof_name: "김영희", review_text: "실습 위주라서 지루하지 않다 다음 학기에도 추천하고 싶다", rating: 4 },
  { course_id: 5, prof_name: "조민재", review_text: "수업이 자주 연기되거나 지각이 잦다 전체적으로 만족스러운 강의였다", rating: 2 },
  { course_id: 6, prof_name: "최수진", review_text: "강의 속도가 너무 빨라서 따라가기 힘들다", rating: 2 },
  { course_id: 3, prof_name: "이철수", review_text: "시간 배분이 아쉬운 편이다 전체적으로 만족스러운 강의였다", rating: 3 },
  { course_id: 3, prof_name: "이철수", review_text: "피드백이 느리고 소통이 잘 안 된다 개인적으로는 아쉬운 점도 있었다", rating: 2 },
  { course_id: 4, prof_name: "박민수", review_text: "교재 위주로 차분하게 진행된다", rating: 3 },
  { course_id: 4, prof_name: "박민수", review_text: "학생들 의견을 존중해준다 다음 학기에도 추천하고 싶다", rating: 5 },
  { course_id: 5, prof_name: "조민재", review_text: "강의 속도와 난이도가 적당하다 전체적으로 만족스러운 강의였다", rating: 5 },
  { course_id: 8, prof_name: "윤예린", review_text: "출석 체크 기준이 너무 빡세다 전체적으로 만족스러운 강의였다", rating: 2 },
  { course_id: 5, prof_name: "조민재", review_text: "강의 속도와 난이도가 적당하다 개인적으로는 아쉬운 점도 있었다", rating: 5 },
  { course_id: 7, prof_name: "오지훈", review_text: "난이도는 적당한 편이다 다시 들어도 괜찮을 것 같다", rating: 3 },
  { course_id: 4, prof_name: "박민수", review_text: "시험 난이도가 적당해서 공부한 만큼 점수가 나온다", rating: 5 },
  { course_id: 1, prof_name: "홍길동", review_text: "학생 질문을 끝까지 들어주고 답변도 성실하다 다음 학기에도 추천하고 싶다", rating: 4 },
  { course_id: 2, prof_name: "김영희", review_text: "피드백이 느리고 소통이 잘 안 된다 개인적으로는 아쉬운 점도 있었다", rating: 2 },
  { course_id: 5, prof_name: "조민재", review_text: "숙제 피드백은 간단하게만 해준다", rating: 3 },
  { course_id: 2, prof_name: "김영희", review_text: "평가 방식은 평범한 편이다 개인적으로는 아쉬운 점도 있었다", rating: 3 },
  { course_id: 5, prof_name: "조민재", review_text: "교재 위주로 차분하게 진행된다", rating: 3 },
  { course_id: 5, prof_name: "조민재", review_text: "학생 질문에 짜증내는 느낌이 있다", rating: 2 },
  { course_id: 5, prof_name: "조민재", review_text: "설명은 친절하지만 템포가 느리다 전체적으로 만족스러운 강의였다", rating: 3 },
  { course_id: 2, prof_name: "김영희", review_text: "출석은 크게 빡세지 않다 개인적으로는 아쉬운 점도 있었다", rating: 3 },
  { course_id: 4, prof_name: "박민수", review_text: "피드백이 빠르고 친절하다 개인적으로는 아쉬운 점도 있었다", rating: 4 },
  { course_id: 1, prof_name: "홍길동", review_text: "교재 위주로 차분하게 진행된다 다음 학기에도 추천하고 싶다", rating: 3 },
  { course_id: 1, prof_name: "홍길동", review_text: "수업 준비를 정말 열심히 해오는 게 느껴진다 다시 들어도 괜찮을 것 같다", rating: 5 },
  { course_id: 4, prof_name: "박민수", review_text: "강의 속도와 난이도가 적당하다", rating: 4 },
  { course_id: 8, prof_name: "윤예린", review_text: "학생들 의견을 존중해준다 전체적으로 만족스러운 강의였다", rating: 4 },
  { course_id: 8, prof_name: "윤예린", review_text: "내용은 많은데 기억에 남는 건 별로 없다 다시 들어도 괜찮을 것 같다", rating: 3 },
  { course_id: 7, prof_name: "오지훈", review_text: "수업 준비를 정말 열심히 해오는 게 느껴진다 다시 들어도 괜찮을 것 같다", rating: 4 },
  { course_id: 7, prof_name: "오지훈", review_text: "시험 범위는 명확하게 알려준다 다시 들어도 괜찮을 것 같다", rating: 3 },
  { course_id: 8, prof_name: "윤예린", review_text: "강의 스타일이 호불호가 나뉠 것 같다", rating: 3 },
  { course_id: 4, prof_name: "박민수", review_text: "예시를 많이 들어줘서 이해가 잘 된다", rating: 5 },
  { course_id: 4, prof_name: "박민수", review_text: "과제량은 보통 수준이다", rating: 3 },
  { course_id: 2, prof_name: "김영희", review_text: "시험 범위는 명확하게 알려준다", rating: 3 },
  { course_id: 4, prof_name: "박민수", review_text: "수업 준비를 정말 열심히 해오는 게 느껴진다 다시 들어도 괜찮을 것 같다", rating: 4 },
  { course_id: 2, prof_name: "김영희", review_text: "과제량은 보통 수준이다 다시 들어도 괜찮을 것 같다", rating: 3 },
  { course_id: 8, prof_name: "윤예린", review_text: "시험 난이도가 적당해서 공부한 만큼 점수가 나온다 개인적으로는 아쉬운 점도 있었다", rating: 4 },
  { course_id: 8, prof_name: "윤예린", review_text: "학생들 의견을 존중해준다 다음 학기에도 추천하고 싶다", rating: 5 },
  { course_id: 4, prof_name: "박민수", review_text: "예시를 많이 들어줘서 이해가 잘 된다 다시 들어도 괜찮을 것 같다", rating: 5 },
  { course_id: 7, prof_name: "오지훈", review_text: "수업 시간이 지루하고 졸리다", rating: 1 },
  { course_id: 1, prof_name: "홍길동", review_text: "설명이 모호해서 혼자 다시 공부해야 한다", rating: 2 },
  { course_id: 4, prof_name: "박민수", review_text: "강의 속도와 난이도가 적당하다 전체적으로 만족스러운 강의였다", rating: 5 },
  { course_id: 7, prof_name: "오지훈", review_text: "실무 사례가 많아서 도움이 된다 전체적으로 만족스러운 강의였다", rating: 5 },
  { course_id: 2, prof_name: "김영희", review_text: "내용이 너무 어려운데 설명을 안 해준다", rating: 1 },
  { course_id: 1, prof_name: "홍길동", review_text: "수업 준비를 정말 열심히 해오는 게 느껴진다 전체적으로 만족스러운 강의였다", rating: 4 },
  { course_id: 7, prof_name: "오지훈", review_text: "수업 시간이 지루하고 졸리다 다음 학기에도 추천하고 싶다", rating: 1 },
  { course_id: 1, prof_name: "홍길동", review_text: "수업 분위기가 편안해서 참여하기 좋다 다음 학기에도 추천하고 싶다", rating: 4 },
  { course_id: 5, prof_name: "조민재", review_text: "시험 범위 공지가 늦게 나와 준비하기 어렵다 개인적으로는 아쉬운 점도 있었다", rating: 2 },
  { course_id: 8, prof_name: "윤예린", review_text: "강의 속도와 난이도가 적당하다 전체적으로 만족스러운 강의였다", rating: 5 },
  { course_id: 1, prof_name: "홍길동", review_text: "시간 배분이 아쉬운 편이다 개인적으로는 아쉬운 점도 있었다", rating: 3 },
  { course_id: 1, prof_name: "홍길동", review_text: "교재 위주로 차분하게 진행된다", rating: 3 },
  { course_id: 1, prof_name: "홍길동", review_text: "강의 스타일이 호불호가 나뉠 것 같다 개인적으로는 아쉬운 점도 있었다", rating: 3 },
  { course_id: 3, prof_name: "이철수", review_text: "시험 난이도가 적당해서 공부한 만큼 점수가 나온다 전체적으로 만족스러운 강의였다", rating: 4 },
  { course_id: 2, prof_name: "김영희", review_text: "특별히 좋지도 나쁘지도 않다 전체적으로 만족스러운 강의였다", rating: 3 },
  { course_id: 7, prof_name: "오지훈", review_text: "수업 준비를 정말 열심히 해오는 게 느껴진다 개인적으로는 아쉬운 점도 있었다", rating: 4 },
  { course_id: 1, prof_name: "홍길동", review_text: "특별히 좋지도 나쁘지도 않다 다음 학기에도 추천하고 싶다", rating: 3 },
  { course_id: 6, prof_name: "최수진", review_text: "강의 속도가 너무 빨라서 따라가기 힘들다 전체적으로 만족스러운 강의였다", rating: 2 },
  { course_id: 5, prof_name: "조민재", review_text: "학생 질문에 짜증내는 느낌이 있다 다음 학기에도 추천하고 싶다", rating: 2 },
  { course_id: 6, prof_name: "최수진", review_text: "설명을 차근차근 잘 해준다 개인적으로는 아쉬운 점도 있었다", rating: 5 },
  { course_id: 2, prof_name: "김영희", review_text: "시험 난이도가 적당해서 공부한 만큼 점수가 나온다 개인적으로는 아쉬운 점도 있었다", rating: 4 },
  { course_id: 5, prof_name: "조민재", review_text: "수업 준비를 정말 열심히 해오는 게 느껴진다", rating: 5 },
  { course_id: 4, prof_name: "박민수", review_text: "시험 범위 공지가 늦게 나와 준비하기 어렵다 다음 학기에도 추천하고 싶다", rating: 1 },
  { course_id: 5, prof_name: "조민재", review_text: "설명은 친절하지만 템포가 느리다 개인적으로는 아쉬운 점도 있었다", rating: 3 },
  { course_id: 1, prof_name: "홍길동", review_text: "숙제 피드백은 간단하게만 해준다 개인적으로는 아쉬운 점도 있었다", rating: 3 },
  { course_id: 5, prof_name: "조민재", review_text: "특별히 좋지도 나쁘지도 않다 전체적으로 만족스러운 강의였다", rating: 3 },
  { course_id: 5, prof_name: "조민재", review_text: "수업 준비를 정말 열심히 해오는 게 느껴진다 개인적으로는 아쉬운 점도 있었다", rating: 4 },
  { course_id: 3, prof_name: "이철수", review_text: "시험 범위 공지가 늦게 나와 준비하기 어렵다 다시 들어도 괜찮을 것 같다", rating: 1 },
  { course_id: 4, prof_name: "박민수", review_text: "시험 범위는 명확하게 알려준다 다시 들어도 괜찮을 것 같다", rating: 3 },
  { course_id: 8, prof_name: "윤예린", review_text: "출석 체크 기준이 너무 빡세다", rating: 1 },
  { course_id: 7, prof_name: "오지훈", review_text: "ppt만 읽고 수업을 끝낸다 다시 들어도 괜찮을 것 같다", rating: 1 },
  { course_id: 3, prof_name: "이철수", review_text: "출석은 크게 빡세지 않다 전체적으로 만족스러운 강의였다", rating: 3 },
  { course_id: 8, prof_name: "윤예린", review_text: "시간 배분이 아쉬운 편이다 다음 학기에도 추천하고 싶다", rating: 3 },
  { course_id: 1, prof_name: "홍길동", review_text: "예시를 많이 들어줘서 이해가 잘 된다 개인적으로는 아쉬운 점도 있었다", rating: 4 },
  { course_id: 1, prof_name: "홍길동", review_text: "수업 자료 퀄리티가 떨어진다 다음 학기에도 추천하고 싶다", rating: 1 },
  { course_id: 3, prof_name: "이철수", review_text: "실무 사례가 많아서 도움이 된다", rating: 5 },
  { course_id: 6, prof_name: "최수진", review_text: "강의력이 좋고 전달력이 뛰어나다", rating: 4 },
  { course_id: 6, prof_name: "최수진", review_text: "평가 방식은 평범한 편이다 다음 학기에도 추천하고 싶다", rating: 3 },
  { course_id: 3, prof_name: "이철수", review_text: "실습 위주라서 지루하지 않다 전체적으로 만족스러운 강의였다", rating: 4 },
  { course_id: 7, prof_name: "오지훈", review_text: "학생 질문을 끝까지 들어주고 답변도 성실하다 다음 학기에도 추천하고 싶다", rating: 5 },
  { course_id: 4, prof_name: "박민수", review_text: "학생 질문에 짜증내는 느낌이 있다 다음 학기에도 추천하고 싶다", rating: 1 },
  { course_id: 1, prof_name: "홍길동", review_text: "강의 속도가 너무 빨라서 따라가기 힘들다 다음 학기에도 추천하고 싶다", rating: 1 },
  { course_id: 6, prof_name: "최수진", review_text: "학생 의견을 무시하는 느낌이다 전체적으로 만족스러운 강의였다", rating: 1 },
  { course_id: 1, prof_name: "홍길동", review_text: "과제량은 보통 수준이다 다음 학기에도 추천하고 싶다", rating: 3 },
  { course_id: 6, prof_name: "최수진", review_text: "학생 의견을 무시하는 느낌이다 다시 들어도 괜찮을 것 같다", rating: 1 },
  { course_id: 6, prof_name: "최수진", review_text: "예습을 하면 따라갈 만하다 다음 학기에도 추천하고 싶다", rating: 3 },
  { course_id: 6, prof_name: "최수진", review_text: "예시를 많이 들어줘서 이해가 잘 된다 전체적으로 만족스러운 강의였다", rating: 5 },
  { course_id: 5, prof_name: "조민재", review_text: "예시를 많이 들어줘서 이해가 잘 된다 다시 들어도 괜찮을 것 같다", rating: 5 },
  { course_id: 6, prof_name: "최수진", review_text: "수업 자료 퀄리티가 떨어진다 다음 학기에도 추천하고 싶다", rating: 1 },
  { course_id: 4, prof_name: "박민수", review_text: "ppt만 읽고 수업을 끝낸다", rating: 2 },
  { course_id: 4, prof_name: "박민수", review_text: "피드백이 느리고 소통이 잘 안 된다 다시 들어도 괜찮을 것 같다", rating: 1 },
  { course_id: 6, prof_name: "최수진", review_text: "숙제 피드백은 간단하게만 해준다", rating: 3 },
  { course_id: 5, prof_name: "조민재", review_text: "출석은 크게 빡세지 않다 다음 학기에도 추천하고 싶다", rating: 3 },
  { course_id: 6, prof_name: "최수진", review_text: "설명이 모호해서 혼자 다시 공부해야 한다 개인적으로는 아쉬운 점도 있었다", rating: 2 },
  { course_id: 3, prof_name: "이철수", review_text: "수업 분위기가 편안해서 참여하기 좋다 전체적으로 만족스러운 강의였다", rating: 5 },
  { course_id: 5, prof_name: "조민재", review_text: "평가가 너무 빡세서 점수 받기가 힘들다 다시 들어도 괜찮을 것 같다", rating: 1 },
  { course_id: 5, prof_name: "조민재", review_text: "수업 분위기가 편안해서 참여하기 좋다 다음 학기에도 추천하고 싶다", rating: 5 },
  { course_id: 8, prof_name: "윤예린", review_text: "수업이 자주 연기되거나 지각이 잦다 개인적으로는 아쉬운 점도 있었다", rating: 1 },
  { course_id: 8, prof_name: "윤예린", review_text: "내용은 많은데 기억에 남는 건 별로 없다", rating: 3 },
  { course_id: 5, prof_name: "조민재", review_text: "시험 범위는 명확하게 알려준다 개인적으로는 아쉬운 점도 있었다", rating: 3 },
  { course_id: 6, prof_name: "최수진", review_text: "실습 위주라서 지루하지 않다 다시 들어도 괜찮을 것 같다", rating: 4 },
  { course_id: 4, prof_name: "박민수", review_text: "학생 질문을 끝까지 들어주고 답변도 성실하다", rating: 4 },
  { course_id: 4, prof_name: "박민수", review_text: "수업 자료 퀄리티가 떨어진다 다음 학기에도 추천하고 싶다", rating: 1 },
  { course_id: 7, prof_name: "오지훈", review_text: "조별과제가 조금 많다 전체적으로 만족스러운 강의였다", rating: 3 },
  { course_id: 7, prof_name: "오지훈", review_text: "피드백이 느리고 소통이 잘 안 된다 전체적으로 만족스러운 강의였다", rating: 1 },
  { course_id: 1, prof_name: "홍길동", review_text: "학생들 의견을 존중해준다 전체적으로 만족스러운 강의였다", rating: 5 },
  { course_id: 3, prof_name: "이철수", review_text: "예습을 하면 따라갈 만하다 다음 학기에도 추천하고 싶다", rating: 3 },
  { course_id: 1, prof_name: "홍길동", review_text: "과제량은 보통 수준이다", rating: 3 },
  { course_id: 8, prof_name: "윤예린", review_text: "학생들 의견을 존중해준다 개인적으로는 아쉬운 점도 있었다", rating: 5 },
  { course_id: 6, prof_name: "최수진", review_text: "수업 자료 퀄리티가 떨어진다 개인적으로는 아쉬운 점도 있었다", rating: 2 },
  { course_id: 8, prof_name: "윤예린", review_text: "중요한 부분을 여러 번 강조해줘서 기억에 남는다 다음 학기에도 추천하고 싶다", rating: 5 },
  { course_id: 5, prof_name: "조민재", review_text: "실습 위주라서 지루하지 않다 개인적으로는 아쉬운 점도 있었다", rating: 5 },
  { course_id: 8, prof_name: "윤예린", review_text: "과제량은 보통 수준이다 다시 들어도 괜찮을 것 같다", rating: 3 },
  { course_id: 8, prof_name: "윤예린", review_text: "중요한 부분을 여러 번 강조해줘서 기억에 남는다 전체적으로 만족스러운 강의였다", rating: 5 },
  { course_id: 5, prof_name: "조민재", review_text: "과제가 너무 많고 기준도 애매하다 전체적으로 만족스러운 강의였다", rating: 1 },
  { course_id: 3, prof_name: "이철수", review_text: "수업 분위기가 편안해서 참여하기 좋다 전체적으로 만족스러운 강의였다", rating: 4 },
  { course_id: 2, prof_name: "김영희", review_text: "피드백이 느리고 소통이 잘 안 된다 개인적으로는 아쉬운 점도 있었다", rating: 2 },
  { course_id: 8, prof_name: "윤예린", review_text: "ppt만 읽고 수업을 끝낸다 다음 학기에도 추천하고 싶다", rating: 1 },
  { course_id: 7, prof_name: "오지훈", review_text: "시간 배분이 아쉬운 편이다", rating: 3 },
  { course_id: 7, prof_name: "오지훈", review_text: "ppt만 읽고 수업을 끝낸다 다시 들어도 괜찮을 것 같다", rating: 2 },
  { course_id: 7, prof_name: "오지훈", review_text: "평가가 너무 빡세서 점수 받기가 힘들다 다음 학기에도 추천하고 싶다", rating: 1 },
  { course_id: 4, prof_name: "박민수", review_text: "피드백이 느리고 소통이 잘 안 된다", rating: 2 },
  { course_id: 7, prof_name: "오지훈", review_text: "수업이 자주 연기되거나 지각이 잦다 전체적으로 만족스러운 강의였다", rating: 2 },
  { course_id: 8, prof_name: "윤예린", review_text: "수업 자료가 잘 정리되어 있다 다음 학기에도 추천하고 싶다", rating: 4 },
  { course_id: 1, prof_name: "홍길동", review_text: "강의력이 좋고 전달력이 뛰어나다 전체적으로 만족스러운 강의였다", rating: 5 },
  { course_id: 8, prof_name: "윤예린", review_text: "설명을 차근차근 잘 해준다 다음 학기에도 추천하고 싶다", rating: 5 },
  { course_id: 6, prof_name: "최수진", review_text: "판서를 깔끔하게 잘 해준다 다시 들어도 괜찮을 것 같다", rating: 5 },
  { course_id: 7, prof_name: "오지훈", review_text: "내용이 너무 어려운데 설명을 안 해준다 다시 들어도 괜찮을 것 같다", rating: 2 },
  { course_id: 2, prof_name: "김영희", review_text: "ppt만 읽고 수업을 끝낸다 다시 들어도 괜찮을 것 같다", rating: 1 },
  { course_id: 4, prof_name: "박민수", review_text: "특별히 좋지도 나쁘지도 않다", rating: 3 },
  { course_id: 1, prof_name: "홍길동", review_text: "강의 속도와 난이도가 적당하다 개인적으로는 아쉬운 점도 있었다", rating: 4 },
  { course_id: 3, prof_name: "이철수", review_text: "학생 질문을 끝까지 들어주고 답변도 성실하다", rating: 5 },
  { course_id: 4, prof_name: "박민수", review_text: "설명이 모호해서 혼자 다시 공부해야 한다 다시 들어도 괜찮을 것 같다", rating: 2 },
  { course_id: 3, prof_name: "이철수", review_text: "조별과제가 조금 많다", rating: 3 },
  { course_id: 3, prof_name: "이철수", review_text: "설명이 두서없고 이해가 잘 안 된다 다시 들어도 괜찮을 것 같다", rating: 1 },
  { course_id: 7, prof_name: "오지훈", review_text: "설명이 모호해서 혼자 다시 공부해야 한다", rating: 1 },
  { course_id: 4, prof_name: "박민수", review_text: "중요한 부분을 여러 번 강조해줘서 기억에 남는다 개인적으로는 아쉬운 점도 있었다", rating: 5 },
  { course_id: 2, prof_name: "김영희", review_text: "설명은 친절하지만 템포가 느리다", rating: 3 },
  { course_id: 6, prof_name: "최수진", review_text: "난이도는 적당한 편이다 다시 들어도 괜찮을 것 같다", rating: 3 },
  { course_id: 2, prof_name: "김영희", review_text: "시험 범위는 명확하게 알려준다 다시 들어도 괜찮을 것 같다", rating: 3 },
  { course_id: 1, prof_name: "홍길동", review_text: "학생 의견을 무시하는 느낌이다", rating: 2 },
  { course_id: 7, prof_name: "오지훈", review_text: "수업이 자주 연기되거나 지각이 잦다 전체적으로 만족스러운 강의였다", rating: 2 },
  { course_id: 7, prof_name: "오지훈", review_text: "중요한 부분을 여러 번 강조해줘서 기억에 남는다 개인적으로는 아쉬운 점도 있었다", rating: 5 },
  { course_id: 8, prof_name: "윤예린", review_text: "피드백이 느리고 소통이 잘 안 된다 다시 들어도 괜찮을 것 같다", rating: 2 },
  { course_id: 4, prof_name: "박민수", review_text: "실무 사례가 많아서 도움이 된다 전체적으로 만족스러운 강의였다", rating: 5 },
  { course_id: 8, prof_name: "윤예린", review_text: "조별과제가 조금 많다 다음 학기에도 추천하고 싶다", rating: 3 },
  { course_id: 6, prof_name: "최수진", review_text: "판서를 깔끔하게 잘 해준다 전체적으로 만족스러운 강의였다", rating: 5 },
  { course_id: 8, prof_name: "윤예린", review_text: "피드백이 빠르고 친절하다 다시 들어도 괜찮을 것 같다", rating: 5 },
  { course_id: 5, prof_name: "조민재", review_text: "시간 배분이 아쉬운 편이다 다시 들어도 괜찮을 것 같다", rating: 3 },
  { course_id: 1, prof_name: "홍길동", review_text: "과제량은 보통 수준이다", rating: 3 },
  { course_id: 4, prof_name: "박민수", review_text: "난이도는 적당한 편이다 다음 학기에도 추천하고 싶다", rating: 3 },
  { course_id: 4, prof_name: "박민수", review_text: "강의 스타일이 호불호가 나뉠 것 같다 다음 학기에도 추천하고 싶다", rating: 3 },
  { course_id: 8, prof_name: "윤예린", review_text: "예시를 많이 들어줘서 이해가 잘 된다 전체적으로 만족스러운 강의였다", rating: 5 },
  { course_id: 7, prof_name: "오지훈", review_text: "과제량은 보통 수준이다 다시 들어도 괜찮을 것 같다", rating: 3 },
  { course_id: 6, prof_name: "최수진", review_text: "평가가 너무 빡세서 점수 받기가 힘들다 다음 학기에도 추천하고 싶다", rating: 2 },
  { course_id: 6, prof_name: "최수진", review_text: "설명이 모호해서 혼자 다시 공부해야 한다 다시 들어도 괜찮을 것 같다", rating: 2 },
  { course_id: 5, prof_name: "조민재", review_text: "강의 속도가 너무 빨라서 따라가기 힘들다 전체적으로 만족스러운 강의였다", rating: 1 },
  { course_id: 6, prof_name: "최수진", review_text: "중요한 부분을 여러 번 강조해줘서 기억에 남는다 전체적으로 만족스러운 강의였다", rating: 4 },
  { course_id: 4, prof_name: "박민수", review_text: "강의 스타일이 호불호가 나뉠 것 같다 다시 들어도 괜찮을 것 같다", rating: 3 },
  { course_id: 5, prof_name: "조민재", review_text: "실습 위주라서 지루하지 않다 다시 들어도 괜찮을 것 같다", rating: 4 },
  { course_id: 4, prof_name: "박민수", review_text: "학생 질문에 짜증내는 느낌이 있다", rating: 2 },
  { course_id: 3, prof_name: "이철수", review_text: "ppt만 읽고 수업을 끝낸다 개인적으로는 아쉬운 점도 있었다", rating: 1 },
  { course_id: 5, prof_name: "조민재", review_text: "내용은 많은데 기억에 남는 건 별로 없다 다음 학기에도 추천하고 싶다", rating: 3 },
  { course_id: 2, prof_name: "김영희", review_text: "수업 자료가 잘 정리되어 있다 다음 학기에도 추천하고 싶다", rating: 5 },
  { course_id: 8, prof_name: "윤예린", review_text: "과제가 너무 많고 기준도 애매하다", rating: 1 },
  { course_id: 5, prof_name: "조민재", review_text: "설명이 두서없고 이해가 잘 안 된다 다음 학기에도 추천하고 싶다", rating: 1 },
  { course_id: 8, prof_name: "윤예린", review_text: "수업 자료가 잘 정리되어 있다 전체적으로 만족스러운 강의였다", rating: 4 },
  { course_id: 3, prof_name: "이철수", review_text: "출석은 크게 빡세지 않다", rating: 3 },
  { course_id: 4, prof_name: "박민수", review_text: "시험 난이도가 적당해서 공부한 만큼 점수가 나온다 개인적으로는 아쉬운 점도 있었다", rating: 5 },
  { course_id: 4, prof_name: "박민수", review_text: "난이도는 적당한 편이다 다음 학기에도 추천하고 싶다", rating: 3 },
  { course_id: 8, prof_name: "윤예린", review_text: "학생 의견을 무시하는 느낌이다 다시 들어도 괜찮을 것 같다", rating: 2 },
  { course_id: 1, prof_name: "홍길동", review_text: "시간 배분이 아쉬운 편이다", rating: 3 },
  { course_id: 4, prof_name: "박민수", review_text: "과제량은 보통 수준이다 다시 들어도 괜찮을 것 같다", rating: 3 },
  { course_id: 2, prof_name: "김영희", review_text: "강의 속도와 난이도가 적당하다 개인적으로는 아쉬운 점도 있었다", rating: 4 },
  { course_id: 2, prof_name: "김영희", review_text: "설명을 차근차근 잘 해준다 다음 학기에도 추천하고 싶다", rating: 5 },
  { course_id: 8, prof_name: "윤예린", review_text: "ppt만 읽고 수업을 끝낸다 다시 들어도 괜찮을 것 같다", rating: 1 },
  { course_id: 5, prof_name: "조민재", review_text: "숙제 피드백은 간단하게만 해준다 다음 학기에도 추천하고 싶다", rating: 3 },
  { course_id: 2, prof_name: "김영희", review_text: "과제량은 보통 수준이다 다시 들어도 괜찮을 것 같다", rating: 3 },
  { course_id: 4, prof_name: "박민수", review_text: "설명이 두서없고 이해가 잘 안 된다 전체적으로 만족스러운 강의였다", rating: 1 },
  { course_id: 5, prof_name: "조민재", review_text: "예시를 많이 들어줘서 이해가 잘 된다 전체적으로 만족스러운 강의였다", rating: 4 },
  { course_id: 5, prof_name: "조민재", review_text: "시간 배분이 아쉬운 편이다 개인적으로는 아쉬운 점도 있었다", rating: 3 },
  { course_id: 5, prof_name: "조민재", review_text: "설명이 두서없고 이해가 잘 안 된다 다시 들어도 괜찮을 것 같다", rating: 2 },
  { course_id: 7, prof_name: "오지훈", review_text: "평가가 너무 빡세서 점수 받기가 힘들다 다음 학기에도 추천하고 싶다", rating: 2 },
  { course_id: 2, prof_name: "김영희", review_text: "수업은 무난한 편이다 다음 학기에도 추천하고 싶다", rating: 3 },
  { course_id: 6, prof_name: "최수진", review_text: "출석은 크게 빡세지 않다", rating: 3 },
  { course_id: 2, prof_name: "김영희", review_text: "강의력이 좋고 전달력이 뛰어나다 다시 들어도 괜찮을 것 같다", rating: 4 },
  { course_id: 1, prof_name: "홍길동", review_text: "판서를 깔끔하게 잘 해준다 다시 들어도 괜찮을 것 같다", rating: 5 },
  { course_id: 3, prof_name: "이철수", review_text: "난이도는 적당한 편이다 다음 학기에도 추천하고 싶다", rating: 3 },
  { course_id: 2, prof_name: "김영희", review_text: "과제가 너무 많고 기준도 애매하다 다시 들어도 괜찮을 것 같다", rating: 2 },
  { course_id: 6, prof_name: "최수진", review_text: "특별히 좋지도 나쁘지도 않다 전체적으로 만족스러운 강의였다", rating: 3 },
];
